### ISSUE TITLE
Possible to set a metadata key within an it block?

### ISSUE THREAD

**Issue by mkarlovich** [ordinaryzelig/minispec-metadata#11]
This works, but not very nice, to set an id tag from within an it block:
`self.class.instance_variable_set(:@describe_metadata, metadata.merge({id: 100}))`
Is there a better way?

**Comment by ordinaryzelig** [comment]
Not sure what your goal is. Can you give a more complete example please?

**Comment by mkarlovich** [comment]
I have a need to set the status of a group of tests as an aggregate to report to an external server.   When the last it block of the group executes, I set a metadata key from within the it block indicating pass or fail for the entire group.  I want to see each individual it block execute so I get individual results reporting as well as this aggregate result.

**Comment by ordinaryzelig** [comment]
I suppose you could use the setter method `self.class.describe_metadata = {id: 100}` instead of `instance_variable_set`.

Not sure I would use metadata for what you're doing, though. If you're tracking the result of tests and want an aggregate of them, take a look at `Minitest::Reporter` and make one of your own. That's what they're meant to do.
